version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: epitrello-postgres
    environment:
      POSTGRES_USER: epitrello
      POSTGRES_PASSWORD: epitrello
      POSTGRES_DB: epitrello
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U epitrello']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
